### ISSUE TITLE
Double Layout Editor 

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#206]
I found some nasty glitch

Appearance > Layouts > Some_New_Theme --> Layout Editor
Layout options > Make Default --> Layout Editor in Layout Editor !!Combo!!

**Comment by juek** [comment]
Thanks. [This commit](https://github.com/Typesetter/Typesetter/commit/3b466b9e0e9e2ccb1500e571a7441dcac622043a) should fix it.

**Comment by mahotilo** [comment]
Sorry, I can't confirm
Clear last TS master. Clear cache. 
And still have this. 

![1](https://user-images.githubusercontent.com/14929385/29126551-58d886e2-7d27-11e7-9f37-bb1b833eb090.png)

**Comment by juek** [comment]
Have you also cleared the browser cache? 
Can you see the changes from the commit when you view 
http://www.test:8080/include/js/theme_content_outer.js
in the browser?

**Comment by mahotilo** [comment]
> Have you also cleared the browser cache?

Yes, I used private window 

> Can you see the changes from the commit when you view
> http://www.test:8080/include/js/theme_content_outer.js
> in the browser?

Yes, I immediately checked it.

> edit2 (off-topic): what do you think about the Cajón theme?

Very cute.
TS needs standard responsive theme with side menu. It really can be default theme after installation.

**Comment by juek** [comment]
Thanks for double checking. Timing was critical, so the check is now recurring (moved into the already existing setInterval function).

OT: Cajón Theme ->  "It really can be default theme after installation" -> Thanks for the compliment! But I don't believe it should be default. It's a bit more complicated to adapt than Bootswatch Scss and the side menu is not exactly 'vanilla' Bootstrap. But I do believe it's good to have a sidemenu theme preinstalled that can handle many top-level pages and multiple menu levels. Folks frequently struggle with multilevel navs.

**Comment by mahotilo** [comment]
> It's a bit more complicated to adapt than Bootswatch Scss and the side menu is not exactly 'vanilla' Bootstrap. 

Hm... I think default theme should't be a platform for for wide modification. It should be "standing dish"or "thumb rule" for ordinary users, who looks for cute ready solution.

And, I am curious how it can be that I can now use CajonParallax in another themes too:)

**Comment by juek** [comment]
> … CajonParallax in another themes too:)

It's sort of a 'noconflict' version of ParallaxImage but doesn't have the 'makeFullWidth" breakout-class in it's combo preset – which only works with centered content. Take it as 'Parallax Image 2.0' preview ;-)

**Comment by mahotilo** [comment]
> Timing was critical, so the check is now recurring (moved into the already existing setInterval function).

Still have problem :( 
But now double side menu and top message  disappears after couple of seconds during page loading.

**Comment by juek** [comment]
> Still have problem :(
> But now double side menu and top message disappears after couple of seconds during page loading.

Does the nested editor stay/reappear after the timeout?

**Comment by mahotilo** [comment]
> Does the nested editor stay/reappear after the timeout?

No, it doesn't appear again. And when I wrote "side menu" I had in mind "side editor"

**Comment by juek** [comment]
> No, it doesn't appear again.

OK, then it's fine. It is quite a dirty fix of what I believe being an old issue (I might be wrong and if so, I'm totally unaware of how I caused it myself). I can't figure out how to prevent the double loading, so it's merely curing the symptom not the cause. Maybe I will stumble upon a better solution some time.

**Comment by juek** [comment]
Can we close the issue? 
Because a 5.1 release is due ;-)

**Comment by mahotilo** [comment]
>  is quite a dirty fix of what I believe being an old issue (

Yes, TS 5.0.3 have it also

> Because a 5.1 release is due ;-)

Yes, we can. 5.1 is first of all!
