### ISSUE TITLE
Bootswatch4_Scss\materia brokes gp_admin_box

### ISSUE THREAD

**Issue by mahotilo** [Typesetter/Typesetter#659]
This is how the section editor looks like with Bootswatch4_Scss\materia 
![image](https://user-images.githubusercontent.com/14929385/89812928-8d6c4500-db49-11ea-9e27-d92e80b9f34b.png)

I think it has to do with to
https://github.com/Typesetter/Typesetter/blob/95092d096f6e45673e73ceb83e5bc75b6fb5c298/themes/Bootswatch4_Scss/materia/style.scss#L435

We have to exclude gp_admin_box from styling

**Comment by juek** [comment]
Materia adds some unusual styles to general form elements. From my point of view that's a no-go. But others will also do such stuff so we have to deal with it and extend our admin ui style normalization in case.

Should be fixed with https://github.com/Typesetter/Typesetter/commit/f6d7b57adedad335a42caeceab158994ea929836

**Comment by mahotilo** [comment]
We are still missing checkboxes. And we have some misalign for elements without checkbox.

![image](https://user-images.githubusercontent.com/14929385/89861315-216ff800-dbae-11ea-8b98-9643723d68f3.png)

> But others will also do such stuff so we have to deal with it and extend our admin ui style normalization in case.

This can be tricky:(

**Comment by juek** [comment]
Could you please try https://github.com/Typesetter/Typesetter/commit/8c10e39f6996fd78d7853444b96f7cfee13fc3b4
(I currently have not enough time to test all platforms and versions)

**Comment by mahotilo** [comment]
Yes, it works fine now

**Comment by mahotilo** [comment]
Another victim:)
Do you see the same?

![image](https://user-images.githubusercontent.com/14929385/89906591-3ff8e200-dbf4-11ea-9d06-b09d28bd4a0b.png)

**Comment by juek** [comment]
Enough is enough. I [banned the spook](https://github.com/Typesetter/Typesetter/commit/70781882be821ed560262ab0a4e8a3b614ad98f0) to the .GPAREA scope :)

**Comment by mahotilo** [comment]
Yep! It fixes all the cases I have found.
It is at the time, because Google began to offer me to read about Shadow DOM:)
